# Generated by Django 5.2 on 2025-05-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_blocks', '0004_auto_20150813_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojoinfoblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalinfoblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
