FROM python:3.14.2-alpine3.23

LABEL description="Image for Django and uwsgi code"

# Create the app directory
RUN mkdir /app && apk update && apk add postgresql18-dev

VOLUME /app/logs

# Set the working directory inside the container
WORKDIR /app

# Set environment variables
# Prevents Python from writing pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1

# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED=1

ENV DJANGO_SETTINGS_MODULE=config.settings.docker

# Upgrade pip
RUN pip install --upgrade pip

COPY ../requirements.txt cohpy /app/

# run this command to install all dependencies
RUN pip install --no-cache-dir -r requirements.txt


#   These can't be part of the build
#    && ./manage.py makemigrations \
#    && ./manage.py migrate


# Expose the Django port
EXPOSE 8000

# Run Django’s development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]