#!/bin/bash

if ((EUID != 0)); then
  	echo "This script should be run via sudo or as root" 1>&2
  	exit 1
fi

if [[ "$PWD" != "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" ]]; then
  	echo "This script must be run from the directory where it resides"
  	exit 1
fi

echo "build of cohpy_org:django disabled"
#docker build -t cohpy_org:django -f Dockerfile-django ..

docker build -t cohpy_org:one_container -f Dockerfile-1container ..