#!/bin/bash

if ((EUID != 0)); then
  	echo "This script should be run via sudo or as root" 1>&2
  	exit 1
fi

echo "run of cohpy_django disabled"
#docker run \
#  -p 8000:8000 \
#  -v cohpy_django_log:/app/logs \
#  cohpy_org:django

#docker run -p 80:80 cohpy_org:one_container

#docker run \
#  -p 80:80 -p 443:443 \
#  -v $(pwd)/prod_setup/nginx/cohpy:/etc/nginx/conf.d/default.conf:ro \
#  -v $(pwd)/prod_setup/nginx/ssl:/etc/nginx/ssl:ro \
#  cohpy_org:one_container

docker run  -p 80:80  cohpy_org:one_container

echo "container should be running now"
