#!/bin/bash

if ((EUID != 0)); then
  	echo "This script should be run via sudo or as root" 1>&2
  	exit 1
fi

echo "run of cohpy_django disabled"
#docker run \
#  -p 8000:8000 \
#  -v cohpy_django_log:/app/logs \
#  cohpy_org:django

docker run -p 80:80 cohpy_org:one_container